extends: airbnb
env:
  browser: true
  node: true
rules:
  import/no-extraneous-dependencies: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-noninteractive-element-interactions: off
  react/no-array-index-key: off
  no-param-reassign: off